import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Sparkles } from 'lucide-react';

export default function CampaignsPage() {
  return (
    <div className="mx-auto max-w-7xl space-y-6 p-6 lg:p-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-display text-2xl font-semibold tracking-tight">Campaigns</h1>
          <p className="text-sm text-muted-foreground">Marketing campaigns generated by the AI Marketing Agent.</p>
        </div>
        <Badge variant="secondary" className="gap-1"><Sparkles className="h-3 w-3" /> Coming soon</Badge>
      </div>
      <Card className="flex flex-col items-center justify-center gap-2 border-dashed border-border bg-card/40 px-6 py-16 text-center backdrop-blur">
        <Sparkles className="h-8 w-8 text-muted-foreground" />
        <p className="text-sm text-muted-foreground">
          Campaigns will appear here once the Marketing module is live.
        </p>
      </Card>
    </div>
  );
}
